### ISSUE TITLE
Upload function does not return file ID

### ISSUE THREAD

**Issue by bombillazo** [supabase/storage-js#170]
# Bug report

- [x] I confirm this is a bug with Supabase, not with my own application. 
- [x] I confirm I have searched the [Docs](https://docs.supabase.com), GitHub [Discussions](https://github.com/supabase/supabase/discussions), and [Discord](https://discord.supabase.com). 

## Describe the bug

Currently, only part of the path (not including the bucket) of the uploaded file is returned even though the API returns both the ID and full path of the file: [source](https://supabase.github.io/storage-api/#/object/post_object__bucketName___wildcard_)

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

Call the `upload` function from the client, which internally uses `uploadOrUpdate` and the response will not include the id of the uploaded file. The direct API does return the id.

## Expected behavior

Developers get back the id of the file uploaded.

## System information

- Version of supabase-js: 2.26.0

**Comment by fenos** [comment]
We are now returning the File ID
#168

**Comment by bombillazo** [comment]
Awesome! Thanks
