### ISSUE TITLE
Rename `SupabaseStorageClient` to `StorageClient`

### ISSUE THREAD

**Issue by mikeanth-dev** [supabase/storage-js#46]
# Chore

## Describe the chore

I think the client name is a bit confusing as it does not match the pattern set by the other modules.
For example:
- in `postgrest-js`, the client is called `PostgrestClient`
- in `gotrue-js`, the client is called `GoTrueClient`
- in `realtime-js`, the client is called `RealtimeClient`

Naturally, I expected the `storage-js` to be called `StorageClient`. Clean, simple, minimal. Gets the point across. I was surprised to see it called `SupabaseStorageClient`.

**Comment by thebengeu** [comment]
Good point, thanks. This would be a breaking change though. For backward compatibility, could you retain a `SupabaseStorageClient` alias in #48?

**Comment by mikeanth-dev** [comment]
Good idea. Will do that tonight!

**Comment by thebengeu** [comment]
> Maybe I could add like a deprecation warning or something?

You mean, like a console message? I don't think it's necessary, and might be noisy. Most usage is indirectly via `supabase-js`, which would be updated to use the new name, and it's no big deal if people continue using the old name, I don't think we'd ever remove it entirely.
