### ISSUE TITLE
Document Return Value for Upload

### ISSUE THREAD

**Issue by Danieltech99** [supabase/storage-js#9]
# Improve documentation

## Link 

[https://supabase.io/docs/reference/javascript/storage-from-upload](https://supabase.io/docs/reference/javascript/storage-from-upload)

## Describe the problem

It was not clear what the return value of the `upload` function was. I ended up logging it to the console then I was unsure what exactly I should use as the path for the `download` function.

It is also unclear to me why the bucket is included in the returned `Key`/path if it is added automatically in the `download` function. 

I was most concerned that if a user had uploaded to a specific folder/subfolder then they could not just take the last piece, they would have to remove the bucket name and first slash every time they wanted to use the download function. (Consider that in most cases, at least in my case, the return value of the `upload` function is immediately stored in a table/row and then used later to download.)

## Describe the improvement

The minimum improvement is explicitly stating on the website that the `upload` function returns `{Key: string}` where the `Key` is a path that includes/is prefixed with the bucket (as made evident after looking at the [code](https://github.com/supabase/storage-js/blob/133ea2ced5ca0dbd8943b55f8aca7fa7b7cc6379/src/lib/StorageFileApi.ts#L254) in this library). It also needs to be explicitly stated the the `download` function does not accept this bucket prefix and it must be removed when passing the path parameter.

It would be even nicer if the upload function returned an additional key/property (so that the `Key` property remains unchanged for backwards compatibility) that returns just the download path (without the bucket) and a separate property for the bucket if desired. The `Key` property can stay unchanged.

This would reduce confusion and developers would not have to parse/split/trim/format the returned value when storing it or using it to download the file.

## Additional context

The original context at which I arrived at this issue was: I was uploading a profile picture to the avatars bucket detailed in the [nextjs-ts-user-management example](https://github.com/supabase/supabase/tree/master/examples/nextjs-ts-user-management) and was storing the returned path in the `avatar_url` column and then rendering the user profile but I was using the returned Key.

**Comment by fenos** [comment]
Closing as this is fixed on V2-rc, thanks for raising the issue!
